service: contacts-srv

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ${file(../serverless-config.json):region}
  apiGateway:
    apiKeys:
      - defaultKey
  httpApi:
    id: !ImportValue NearGatewayHttpApiId
  #TODO: Need to remove extra permissions
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:BatchGet*
            - dynamodb:DescribeStream
            - dynamodb:DescribeTable
            - dynamodb:Get*
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:BatchWrite*
            - dynamodb:CreateTable
            - dynamodb:Delete*
            - dynamodb:Update*
            - dynamodb:PutItem
          Resource: "arn:aws:dynamodb:*:*:*"

functions:
  createContact:
    handler: create.main
    events:
     - httpApi:
         path: /contacts
         method: post
  detailContact:
    handler: details.main
    events:
     - httpApi:
         path: /contacts/{contactId}
         method: get
  updateContact:
    handler: update.main
    events:
     - httpApi: 
         path: /contacts/{contactId}
         method: put
  deleteContact:
    handler: delete.main
    events:
     - httpApi: 
         path: /contacts/{contactId}
         method: delete
  listContact:
    handler: list.main
    events:
     - httpApi: 
         path: /contacts/list
         method: get

plugins:
  - serverless-offline
  - serverless-dynamodb-local

#custom:
#  dynamodb:
#      stages: 
#         - dev
#      start: 
#         port: 8000
#         inMemory: false
#         migrate: true

# uncomment for testing 
#resources: 
#  Resources:
#    contactTable:
#      Type: AWS::DynamoDB::Table
#      Properties:
#        TableName: near-contacts
#       AttributeDefinitions:
#          - AttributeName: contactId
#            AttributeType: S
#        KeySchema:
#          - AttributeName: contactId
#            KeyType: HASH
#        ProvisionedThroughput:
#          ReadCapacityUnits: 1
#         WriteCapacityUnits: 1