verifyHash:
  handler: lambda/verifyHash/index.handler
  description: "Takes an id, fingerPrint and check if they exist in database"
  events:
    - httpApi:
        path: /hashes/verify
        method: post
## TODO: fix Error: Serverless Offline only supports retrieving JWT from the headers
#        authorizer:
#          type: jwt
#          id: !ImportValue NearGatewayAuthorizerId
  environment:
    TABLE_NAME_HASHES: near-hashes
  iamRoleStatementsInherit: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
      Resource:
        ## TODO: use ${ssm:/dynamodb/hash-service/hashes/arn} when exported by Terraform
        - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/near-hashes

